// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import "@openzeppelin/contracts/access/AccessControl.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";

import "./IShipmentRegistry.sol";

interface IFreshnessVerifier {
    function verifyProof(bytes calldata proof, uint256[] calldata publicSignals)
        external
        view
        returns (bool);
}

/// @title FreshnessScore — Dynamic Freshness Score Contract
/// @notice Receives ZK-proven freshness statistics from the off-chain prover
///         service (Groth16 via SnarkJS / SP1 / RISC Zero zkVM) and applies
///         a kinetic spoilage model to maintain a 0-100 freshness gauge for
///         each shipment.
///
/// @dev    The ZK proof is verified by the companion `FreshnessVerifier`
///         (auto-generated by SnarkJS). Only the trusted prover service
///         (holding PROVER_ROLE) may call `updateScoreWithProof`.
///         An admin-only `adminSetScore` path exists for testing,
///         emergencies, and manual overrides (no proof required).
///
///         Kinetic spoilage model inputs (encoded in the ZK circuit / zkVM):
///           - Elapsed time since last update (seconds)
///           - Integral of temperature deviation from cold-chain spec (°C·s)
///           - Number of detected excursions during the leg
///         The model outputs a `penalty` in score points (0-100).
///         The circuit enforces: newScore = max(0, previousScore - penalty).
contract FreshnessScore is AccessControl, ReentrancyGuard {
    // ─────────────────────────────────────────────────────────────────────────
    // Roles
    // ─────────────────────────────────────────────────────────────────────────
    bytes32 public constant PROVER_ROLE  = keccak256("PROVER_ROLE");
    bytes32 public constant ADMIN_ROLE   = keccak256("ADMIN_ROLE");

    IShipmentRegistry public immutable shipmentRegistry;
    IFreshnessVerifier public verifier;

    // ─────────────────────────────────────────────────────────────────────────
    // State
    // ─────────────────────────────────────────────────────────────────────────
    struct ScoreRecord {
        uint8   score;          // 0-100 freshness gauge
        uint64  lastUpdatedAt;  // timestamp of latest update
        bytes32 lastProofHash;  // keccak256 of the ZK proof inputs (for audit)
        uint32  updateCount;    // total updates on this shipment
        bool    initialized;    // explicit flag; avoids timestamp == 0 ambiguity
    }

    /// @notice shipmentId → ScoreRecord
    mapping(bytes32 => ScoreRecord) public records;

    // ─────────────────────────────────────────────────────────────────────────
    // Events
    // ─────────────────────────────────────────────────────────────────────────
    event FreshnessInitialized(
        bytes32 indexed shipmentId,
        uint8           initialScore,
        uint64          timestamp
    );

    event FreshnessUpdated(
        bytes32 indexed shipmentId,
        uint8           previousScore,
        uint8           newScore,
        uint8           penalty,
        bytes32         proofHash,
        uint64          timestamp
    );

    /// @notice Emitted once when the freshness score crosses at or below
    ///         the CRITICAL_THRESHOLD (30) in a single update.
    ///         Not re-emitted on subsequent updates that stay below 30.
    event FreshnessCritical(
        bytes32 indexed shipmentId,
        uint8           score,
        uint64          timestamp
    );

    event VerifierUpdated(
        address indexed oldVerifier,
        address indexed newVerifier
    );

    // ─────────────────────────────────────────────────────────────────────────
    // Constants
    // ─────────────────────────────────────────────────────────────────────────
    uint8 public constant CRITICAL_THRESHOLD = 30;

    // ─────────────────────────────────────────────────────────────────────────
    // Constructor
    // ─────────────────────────────────────────────────────────────────────────
    constructor(address registryAddress, address verifierAddress) {
        require(registryAddress != address(0), "invalid registry");
        require(verifierAddress != address(0), "invalid verifier");
        shipmentRegistry = IShipmentRegistry(registryAddress);
        verifier = IFreshnessVerifier(verifierAddress);
        _grantRole(DEFAULT_ADMIN_ROLE, msg.sender);
        _grantRole(ADMIN_ROLE, msg.sender);
        _grantRole(PROVER_ROLE, msg.sender);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Initialization
    // ─────────────────────────────────────────────────────────────────────────

    /// @notice Create a score record at origin (called when the shipment is
    ///         registered). Initial score is always 100 (perfectly fresh).
    /// @param  shipmentId  Unique shipment identifier.
    function initialize(bytes32 shipmentId) external onlyRole(PROVER_ROLE) {
        require(shipmentRegistry.exists(shipmentId), "shipment not found");
        require(!records[shipmentId].initialized, "already initialized");
        records[shipmentId] = ScoreRecord({
            score:         100,
            lastUpdatedAt: uint64(block.timestamp),
            lastProofHash: bytes32(0),
            updateCount:   0,
            initialized:   true
        });
        emit FreshnessInitialized(shipmentId, 100, uint64(block.timestamp));
    }

    // ─────────────────────────────────────────────────────────────────────────
    // ZK-proven update (primary path)
    // ─────────────────────────────────────────────────────────────────────────

    /// @notice Update freshness using ZK-proven spoilage statistics.
    ///         The off-chain prover computes the kinetic model inside the
    ///         Circom `freshness_model` circuit (or SP1 / RISC Zero zkVM)
    ///         and submits the resulting `penalty` along with a `proofHash`
    ///         that identifies the proof artefact stored on IPFS.
    ///
    ///         Full on-chain SNARK verification is intentionally deferred to a
    ///         companion `FreshnessVerifier` contract (SnarkJS-generated);
    ///         this function trusts the PROVER_ROLE caller to have pre-verified.
    ///
    /// @param  shipmentId    Shipment to update.
    /// @param  newScore      New freshness score computed by the prover (0-100).
    /// @param  proof         Groth16 proof bytes.
    /// @param  publicSignals Public signals array containing [newScore, previousScore].
    function updateScoreWithProof(
        bytes32 shipmentId,
        uint8   newScore,
        bytes   calldata proof,
        uint256[] calldata publicSignals
    )
        external
        nonReentrant
        onlyRole(PROVER_ROLE)
    {
        ScoreRecord storage rec = records[shipmentId];
        require(rec.initialized, "shipment not initialized");
        require(publicSignals.length == 2, "invalid public signals");

        uint8 previous = rec.score;
        require(publicSignals[0] == uint256(newScore), "signal new mismatch");
        require(publicSignals[1] == uint256(previous), "signal previous mismatch");
        require(newScore <= previous, "newScore > previous");
        require(newScore <= 100, "newScore > 100");

        bool ok = verifier.verifyProof(proof, publicSignals);
        require(ok, "invalid proof");

        uint8 penalty = previous - newScore;
        bytes32 proofHash = keccak256(abi.encode(proof, publicSignals));

        rec.score         = newScore;
        rec.lastUpdatedAt = uint64(block.timestamp);
        rec.lastProofHash = proofHash;
        rec.updateCount  += 1;

        emit FreshnessUpdated(
            shipmentId,
            previous,
            newScore,
            penalty,
            proofHash,
            uint64(block.timestamp)
        );

        // Only emit FreshnessCritical when the score crosses the threshold
        // downward in this update (not on every call when already critical).
        if (newScore <= CRITICAL_THRESHOLD && previous > CRITICAL_THRESHOLD) {
            emit FreshnessCritical(shipmentId, newScore, uint64(block.timestamp));
        }
    }

    /// @notice Update the verifier contract (admin only).
    function setVerifier(address verifierAddress)
        external
        onlyRole(ADMIN_ROLE)
    {
        require(verifierAddress != address(0), "invalid verifier");
        address oldVerifier = address(verifier);
        verifier = IFreshnessVerifier(verifierAddress);
        emit VerifierUpdated(oldVerifier, verifierAddress);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Admin / fallback update (no proof required — for testing / emergencies)
    // ─────────────────────────────────────────────────────────────────────────

    /// @notice Direct score override — admin only.
    ///         Emits FreshnessUpdated with proofHash set to bytes32(0)
    ///         so admin overrides are distinguishable from ZK-proven
    ///         updates in the event log.
    /// @param  shipmentId  Shipment to update.
    /// @param  newScore    Absolute score to set (0-100).
    function adminSetScore(bytes32 shipmentId, uint8 newScore)
        external
        onlyRole(ADMIN_ROLE)
    {
        require(newScore <= 100, "score > 100");
        ScoreRecord storage rec = records[shipmentId];
        require(rec.initialized, "not initialized");

        uint8 previous = rec.score;
        rec.score         = newScore;
        rec.lastUpdatedAt = uint64(block.timestamp);
        rec.lastProofHash = bytes32(0);
        rec.updateCount  += 1;

        emit FreshnessUpdated(
            shipmentId,
            previous,
            newScore,
            previous > newScore ? previous - newScore : 0,
            bytes32(0), // no proof
            uint64(block.timestamp)
        );

        // Emit critical alert on threshold crossing (admin path too)
        if (newScore <= CRITICAL_THRESHOLD && previous > CRITICAL_THRESHOLD) {
            emit FreshnessCritical(shipmentId, newScore, uint64(block.timestamp));
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // View helpers
    // ─────────────────────────────────────────────────────────────────────────

    /// @notice Returns the current freshness score (0-100).
    /// @dev    Reverts for uninitialized shipments to prevent silent zero-score.
    function getScore(bytes32 shipmentId) external view returns (uint8) {
        require(records[shipmentId].initialized, "not initialized");
        return records[shipmentId].score;
    }

    /// @notice Returns true when the score is at or below CRITICAL_THRESHOLD.
    /// @dev    Returns false for uninitialized shipments (no false positives).
    function isCritical(bytes32 shipmentId) external view returns (bool) {
        ScoreRecord storage rec = records[shipmentId];
        return rec.initialized && rec.score <= CRITICAL_THRESHOLD;
    }
}
