<# 
  deploy-ganache.ps1
  Deploys all VeritasChain contracts to local Ganache using Forge.

  Prerequisites:
    1. Ganache running on http://127.0.0.1:7545
    2. Foundry (forge) installed: https://book.getfoundry.sh/
    3. Run from the repository root: .\scripts\deploy-ganache.ps1

  Usage:
    .\scripts\deploy-ganache.ps1 [-PrivateKey <key>]
    
  If no private key is provided, uses Ganache's default first account key.
#>

param(
    [string]$PrivateKey = "0x4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d"
)

$ErrorActionPreference = "Stop"

$RPC_URL = "http://127.0.0.1:7545"
$FOUNDRY_DIR = Join-Path $PSScriptRoot "..\contracts\foundry"
$ENV_FILE = Join-Path $PSScriptRoot "..\apps\edge-pwa\.env.local"

Write-Host "`n=== VeritasChain Ganache Deployment ===" -ForegroundColor Cyan
Write-Host "RPC:      $RPC_URL"
Write-Host "Foundry:  $FOUNDRY_DIR"
Write-Host ""

# Check Ganache is running
try {
    $null = Invoke-WebRequest -Uri $RPC_URL -Method POST -Body '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' -ContentType "application/json" -TimeoutSec 3
    Write-Host "[OK] Ganache is running" -ForegroundColor Green
} catch {
    Write-Host "[ERROR] Ganache not reachable at $RPC_URL" -ForegroundColor Red
    Write-Host "  Start Ganache GUI or run: npx ganache --port 7545 --chain.chainId 1337" -ForegroundColor Yellow
    exit 1
}

# Build contracts
Write-Host "`nBuilding contracts..." -ForegroundColor Yellow
Push-Location $FOUNDRY_DIR
try {
    forge build
    if ($LASTEXITCODE -ne 0) { throw "forge build failed" }
    Write-Host "[OK] Contracts compiled" -ForegroundColor Green
} finally {
    Pop-Location
}

# Deploy
Write-Host "`nDeploying contracts..." -ForegroundColor Yellow
Push-Location $FOUNDRY_DIR
try {
    $output = forge script script/Deploy.s.sol `
        --rpc-url $RPC_URL `
        --private-key $PrivateKey `
        --broadcast `
        2>&1 | Out-String

    Write-Host $output

    # Parse deployed addresses from forge output
    $registryAddr = if ($output -match "ShipmentRegistry:\s+(0x[0-9a-fA-F]{40})") { $Matches[1] } else { "" }
    $dwhAddr      = if ($output -match "DWHVerifier:\s+(0x[0-9a-fA-F]{40})") { $Matches[1] } else { "" }
    $freshnessAddr = if ($output -match "FreshnessScore:\s+(0x[0-9a-fA-F]{40})") { $Matches[1] } else { "" }

    if ($registryAddr -and $dwhAddr -and $freshnessAddr) {
        Write-Host "`n[OK] All contracts deployed!" -ForegroundColor Green
        Write-Host "  ShipmentRegistry: $registryAddr"
        Write-Host "  DWHVerifier:      $dwhAddr"
        Write-Host "  FreshnessScore:   $freshnessAddr"

        # Write .env.local
        $envContent = @"
# VeritasChain contract addresses (auto-generated by deploy-ganache.ps1)
VITE_REGISTRY_ADDRESS=$registryAddr
VITE_DWH_ADDRESS=$dwhAddr
VITE_FRESHNESS_ADDRESS=$freshnessAddr
VITE_CONTRACT_ADDRESS=$dwhAddr
"@
        Set-Content -Path $ENV_FILE -Value $envContent -Encoding utf8
        Write-Host "`n[OK] Written to $ENV_FILE" -ForegroundColor Green
        Write-Host "  Restart the dev server (pnpm run dev) to pick up the new addresses." -ForegroundColor Yellow
    } else {
        Write-Host "`n[WARN] Could not parse all addresses from forge output." -ForegroundColor Yellow
        Write-Host "  Manually copy addresses from the output above to $ENV_FILE" -ForegroundColor Yellow
    }
} finally {
    Pop-Location
}

Write-Host "`nDone!" -ForegroundColor Cyan
